--// Damage Module //--

StyleMeter.module.Damage = {
	["SWING_DAMAGE"] = {
		["spellId"] = 6603,
		["spellName"] = "Auto Attack",
		["spellSchool"] = 1,
		["amount"] = "arg12",
		["overkill"] = "arg13",
		["school"] = "arg14",
		["resisted"] = "arg15",
		["blocked"] = "arg16",
		["absorbed"] = "arg17",
		["critical"] = "arg18",
		["glancing"] = "arg19",
		["crushing"] = "arg20",
		["isOffHand"] = "arg21",
	},
	["RANGE_DAMAGE"] = {
		["spellId"] = "arg12",
		["spellName"] = "arg13",
		["spellSchool"] = "arg14",
		["amount"] = "arg15",
		["overkill"] = "arg16",
		["school"] = "arg17",
		["resisted"] = "arg18",
		["blocked"] = "arg19",
		["absorbed"] = "arg20",
		["critical"] = "arg21",
		["glancing"] = "arg22",
		["crushing"] = "arg23",
		["isOffHand"] = "arg24",
	},
	["SPELL_DAMAGE"] = {
		["spellId"] = "arg12",
		["spellName"] = "arg13",
		["spellSchool"] = "arg14",
		["amount"] = "arg15",
		["overkill"] = "arg16",
		["school"] = "arg17",
		["resisted"] = "arg18",
		["blocked"] = "arg19",
		["absorbed"] = "arg20",
		["critical"] = "arg21",
		["glancing"] = "arg22",
		["crushing"] = "arg23",
		["isOffHand"] = "arg24",
	},
	["SPELL_PERIODIC_DAMAGE"] = {
		["spellId"] = "arg12",
		["spellName"] = "arg13",
		["spellSchool"] = "arg14",
		["amount"] = "arg15",
		["overkill"] = "arg16",
		["school"] = "arg17",
		["resisted"] = "arg18",
		["blocked"] = "arg19",
		["absorbed"] = "arg20",
		["critical"] = "arg21",
		["glancing"] = "arg22",
		["crushing"] = "arg23",
		["isOffHand"] = "arg24",
	},
}